In [1]:
import pandas as pd
import numpy as np
import matplotlib
from matplotlib import pyplot as plt
matplotlib.style.use('ggplot')
%matplotlib inline

In [2]:
from sklearn.datasets import load_boston
boston = load_boston()

In [3]:
X = boston['data']
Y = boston['target']

In [4]:
from sklearn import model_selection
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X,Y,test_size=0.25,shuffle = False)

In [5]:
from sklearn.tree import DecisionTreeRegressor

In [6]:
def derivation(Y_true,Y_predict):
    return -(Y_predict-Y_true)

In [7]:
def gbm_predict(X):
    return [sum([coeff * algo.predict([x])[0] for algo, coeff
                 in zip(base_algorithms_list, coefficients_list)]) for x in X]

In [8]:
base_algorithms_list = []
coefficients_list = [0.9]

In [9]:
b = DecisionTreeRegressor(max_depth=5, random_state=42)
b.fit(X_train,Y_train)
base_algorithms_list.append(b)

for i in range(49):
    b = DecisionTreeRegressor(max_depth=5, random_state=42)
    Y_predict = gbm_predict(X_train)
    b.fit(X_train, derivation(Y_train,Y_predict))
    base_algorithms_list.append(b)
    coefficients_list.append(0.9)

In [10]:
from sklearn.metrics import mean_squared_error

In [11]:
print(mean_squared_error(Y_test,gbm_predict(X_test))**0.5)

5.476650974168948


In [40]:
X_train[0]

array([6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01, 6.575e+00,
       6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02,
       4.980e+00])

In [37]:
([algo.predict([X[0]]) for algo, coeff in
           zip(base_algorithms_list, coefficients_list)]) 

[array([26.78]),
 array([-0.102]),
 array([0.37364938]),
 array([0.38504866]),
 array([0.09983333]),
 array([-0.69281972]),
 array([0.5370345]),
 array([-0.13254781]),
 array([0.03362462]),
 array([-0.21320814]),
 array([-0.4541274]),
 array([0.02390766]),
 array([0.01039084]),
 array([0.01057786]),
 array([-0.01322805]),
 array([0.0125799]),
 array([-0.06285218]),
 array([-0.06664047]),
 array([0.12369932]),
 array([0.10322737]),
 array([0.00942027]),
 array([0.00141319]),
 array([-0.04350827]),
 array([-0.06819802]),
 array([-0.00512764]),
 array([0.00249511]),
 array([0.05912679]),
 array([-0.04059399]),
 array([-0.00051049]),
 array([0.00569042]),
 array([-0.0016744]),
 array([0.00517783]),
 array([-0.00052004]),
 array([-0.01000182]),
 array([-0.00811404]),
 array([-0.00197257]),
 array([-0.00130994]),
 array([0.00230768]),
 array([0.0011638]),
 array([-0.0006613]),
 array([0.0025896]),
 array([0.00060413]),
 array([-0.00505083]),
 array([0.00266193]),
 array([-0.00011584]),
 arra